const SemifolioDatas = [
  {
    id: 1,
    title: "스팩폴리오 웹디자인 8팀",
    category: "웹디자인",
    imageUrl: "/home/semifolio/1.png",
    userProfile: "/home/semifolio/userImg1.png",
    userName: "이자인",
    likes: 3,
    views: 5,
    style: "심플한",
    color: "337AFF",
    pick: true
  },
  {
    id: 2,
    title: "2021 ASYAAF",
    category: "그래픽디자인",
    imageUrl: "/home/semifolio/2.jpg",
    userProfile: "https://picsum.photos/1021",
    userName: "최지현",
    likes: 35,
    views: 235,
    style: "차가운",
    color: "37A3D",
    pick: true,
  },
  { 
    id: 3,
    title: "小红书 阳台改造箱",
    category: "산업디자인",
    imageUrl: "/home/semifolio/3.jpg",
    userProfile: "https://picsum.photos/1031",
    userName: "REDesign official",
    likes: 33,
    views: 45,
    style: "감성적인",
    color: "B5824E",
    pick: true,
  },
  {
    id: 4,
    title: "Sonus Festival",
    category: "그래픽디자인",
    imageUrl: "/home/semifolio/4.jpg",
    userProfile: "https://picsum.photos/1041",
    userName: "Tim Tijink",
    likes: 32,
    views: 53,
    style: "다채로운",
    color: "01B72E",
    pick: true,
  },
  {
    id: 5,
    title: "PiCKA",
    category: "산업디자인",
    imageUrl: "/home/semifolio/5.png",
    userProfile: "https://picsum.photos/1051",
    userName: "다수의 크리에이터",
    likes: 33,
    views: 523,
    style: "심플한",
    color: "D6D6D6",
    pick: true,
  },
  {
    id: 6,
    title: "During - Branding and Packaging Design - New York",
    category: "브랜딩",
    imageUrl: "/home/semifolio/6.jpg",
    userProfile: "https://picsum.photos/1061",
    userName: "다수의 크리에이터",
    likes: 3,
    views: 5,
    style: "따뜻한",
    color: "C95F2B",
    pick: true,
  },
  {
    id: 7,
    title: "3D ALBUM ART & VISUALIZER OF ZIOR PARK",
    category: "3D디자인",
    imageUrl: "/home/semifolio/7.jpg",
    userProfile: "https://picsum.photos/1071",
    userName: "다수의 크리에이터",
    likes: 35,
    views: 235,
    style: "따뜻한",
    color: "CE6F46",
    pick: true,
  },
  {
    id: 8,
    title: "미라클햇님",
    category: "UI/UX",
    imageUrl: "/home/semifolio/8.png",
    userProfile: "https://picsum.photos/1081",
    userName: "다수의 크리에이터",
    likes: 33,
    views: 45,
    style: "따뜻한",
    color: "EF7300",
  },
  {
    id: 9,
    title: "Christmas Illustrations 2023",
    category: "일러스트레이션",
    imageUrl: "/home/semifolio/9.jpg",
    userProfile: "https://picsum.photos/1091",
    userName: "Martin Naumann",
    likes: 32,
    views: 53,
    style: "역동적인",
    color: "C68641",
    pick: true,
  },
  {
    id: 10,
    title: "Porsche 992 Sport Classic",
    category: "산업디자인",
    imageUrl: "/home/semifolio/10.jpg",
    userProfile: "https://picsum.photos/1101",
    userName: "Brandon Lim",
    likes: 33,
    views: 523,
    style: "역동적인",
    color: "090C13",
    pick: true,
  },
  {
    id: 11,
    title: "Antodo",
    category: "웹디자인",
    imageUrl: "/home/semifolio/11.jpg",
    userProfile: "https://picsum.photos/1111",
    userName: "다수의 크리에이터",
    likes: 33,
    views: 523,
    style: "심플한",
    color: "70C9FF",
    pick: true,
  },
  {
    id: 12,
    title: "zest",
    category: "그래픽디자인",
    imageUrl: "/home/semifolio/12.png",
    userProfile: "https://picsum.photos/1121",
    userName: "Damiao Giovani",
    likes: 33,
    views: 523,
    style: "다채로운",
    color: "33D302",
    pick: true,
  },
  {
    id: 13,
    title: "Mobile App UIUX",
    category: "UI/UX",
    imageUrl: "/home/semifolio/13.png",
    userProfile: "https://picsum.photos/1131",
    userName: "Ravindra Sandun",
    likes: 33,
    views: 523,
    style: "다채로운",
    color: "000000",
  },
  {
    id: 14,
    title: "Investar Web Site Design",
    category: "웹디자인",
    imageUrl: "/home/semifolio/14.png",
    userProfile: "https://picsum.photos/1141",
    userName: "HALO LAB",
    likes: 33,
    views: 523,
    style: "따뜻한",
    color: "70C9FF",
    pick: true,
  },
  {
    id: 15,
    title: "CGV_UXUI Redesign Concept",
    category: "웹디자인",
    imageUrl: "/home/semifolio/15.png",
    userProfile: "https://picsum.photos/1151",
    userName: "taehyn kang",
    likes: 33,
    views: 523,
    style: "심플한",
    color: "FFFFFF",
  },
  {
    id: 16,
    title: "파마씨",
    category: "그래픽디자인",
    imageUrl: "/home/semifolio/16.jpg",
    userProfile: "https://picsum.photos/1161",
    userName: "고원보",
    likes: 33,
    views: 523,
    style: "심플한",
    color: "70C9FF",
  },
  {
    id: 17,
    title: "UIUX",
    category: "UI/UX",
    imageUrl: "/home/semifolio/17.jpg",
    userProfile: "https://picsum.photos/1171",
    userName: "다수의 크리에이터",
    likes: 33,
    views: 523,
    style: "다채로운",
    color: "FFFFFF",
  },
  {
    id: 18,
    title: "삼성카드 웹리뉴얼",
    category: "UI/UX",
    imageUrl: "/home/semifolio/18.jpg",
    userProfile: "https://picsum.photos/1181",
    userName: "Star",
    likes: 33,
    views: 523,
    style: "심플한",
    color: "FFFFFF",
  },
  {
    id: 19,
    title: "Plofello",
    category: "UI/UX",
    imageUrl: "/home/semifolio/19.jpg",
    userProfile: "https://picsum.photos/1191",
    userName: "다수의 크리에이터",
    likes: 33,
    views: 523,
    style: "심플한",
    color: "FFFFFF",
  },
  {
    id: 20,
    title: "'Handmade' Greyscalegorilla Plus",
    category: "산업디자인",
    imageUrl: "/home/semifolio/20.jpg",
    userProfile: "https://picsum.photos/1201",
    userName: "Dan Zucco",
    likes: 33,
    views: 523,
    style: "다채로운",
    color: "FFF500",
    pick: true,
  },
  {
    id: 21,
    title: "스팩폴리오 웹디자인 8팀",
    category: "웹디자인",
    imageUrl: "/home/semifolio/1.png",
    userProfile: "https://picsum.photos/1001",
    userName: "다수의 크리에이터",
    likes: 3,
    views: 5,
    style: "심플한",
    color: "337AFF",
    pick: true
  },
  {
    id: 22,
    title: "2021 ASYAAF",
    category: "그래픽디자인",
    imageUrl: "/home/semifolio/2.jpg",
    userProfile: "https://picsum.photos/1021",
    userName: "최지현",
    likes: 35,
    views: 235,
    style: "차가운",
    color: "37A3D",
    pick: true,
  },
  { 
    id: 23,
    title: "小红书 阳台改造箱",
    category: "산업디자인",
    imageUrl: "/home/semifolio/3.jpg",
    userProfile: "https://picsum.photos/1031",
    userName: "REDesign official",
    likes: 33,
    views: 45,
    style: "감성적인",
    color: "B5824E",
    pick: true,
  },
  {
    id: 24,
    title: "Sonus Festival",
    category: "그래픽디자인",
    imageUrl: "/home/semifolio/4.jpg",
    userProfile: "https://picsum.photos/1041",
    userName: "Tim Tijink",
    likes: 32,
    views: 53,
    style: "다채로운",
    color: "01B72E",
    pick: true,
  },
  {
    id: 25,
    title: "PiCKA",
    category: "산업디자인",
    imageUrl: "/home/semifolio/5.png",
    userProfile: "https://picsum.photos/1051",
    userName: "다수의 크리에이터",
    likes: 33,
    views: 523,
    style: "심플한",
    color: "D6D6D6",
    pick: true,
  },
  {
    id: 26,
    title: "During - Branding and Packaging Design - New York",
    category: "브랜딩",
    imageUrl: "/home/semifolio/6.jpg",
    userProfile: "https://picsum.photos/1061",
    userName: "다수의 크리에이터",
    likes: 3,
    views: 5,
    style: "따뜻한",
    color: "C95F2B",
    pick: true,
  },
  {
    id: 27,
    title: "3D ALBUM ART & VISUALIZER OF ZIOR PARK",
    category: "3D디자인",
    imageUrl: "/home/semifolio/7.jpg",
    userProfile: "https://picsum.photos/1071",
    userName: "다수의 크리에이터",
    likes: 35,
    views: 235,
    style: "따뜻한",
    color: "CE6F46",
    pick: true,
  },
  {
    id: 28,
    title: "미라클햇님",
    category: "UI/UX",
    imageUrl: "/home/semifolio/8.png",
    userProfile: "https://picsum.photos/1081",
    userName: "다수의 크리에이터",
    likes: 33,
    views: 45,
    style: "따뜻한",
    color: "EF7300",
  },
  {
    id: 29,
    title: "Christmas Illustrations 2023",
    category: "일러스트레이션",
    imageUrl: "/home/semifolio/9.jpg",
    userProfile: "https://picsum.photos/1091",
    userName: "Martin Naumann",
    likes: 32,
    views: 53,
    style: "역동적인",
    color: "C68641",
    pick: true,
  },
  {
    id: 30,
    title: "Porsche 992 Sport Classic",
    category: "산업디자인",
    imageUrl: "/home/semifolio/10.jpg",
    userProfile: "https://picsum.photos/1101",
    userName: "Brandon Lim",
    likes: 33,
    views: 523,
    style: "역동적인",
    color: "090C13",
    pick: true,
  },
  {
    id: 31,
    title: "Antodo",
    category: "웹디자인",
    imageUrl: "/home/semifolio/11.jpg",
    userProfile: "https://picsum.photos/1111",
    userName: "다수의 크리에이터",
    likes: 33,
    views: 523,
    style: "심플한",
    color: "70C9FF",
    pick: true,
  },
  {
    id: 32,
    title: "zest",
    category: "그래픽디자인",
    imageUrl: "/home/semifolio/12.png",
    userProfile: "https://picsum.photos/1121",
    userName: "Damiao Giovani",
    likes: 33,
    views: 523,
    style: "다채로운",
    color: "33D302",
    pick: true,
  },
  {
    id: 33,
    title: "Mobile App UIUX",
    category: "UI/UX",
    imageUrl: "/home/semifolio/13.png",
    userProfile: "https://picsum.photos/1131",
    userName: "Ravindra Sandun",
    likes: 33,
    views: 523,
    style: "다채로운",
    color: "000000",
  },
  {
    id: 34,
    title: "Investar Web Site Design",
    category: "웹디자인",
    imageUrl: "/home/semifolio/14.png",
    userProfile: "https://picsum.photos/1141",
    userName: "HALO LAB",
    likes: 33,
    views: 523,
    style: "따뜻한",
    color: "70C9FF",
    pick: true,
  },
  {
    id: 35,
    title: "CGV_UXUI Redesign Concept",
    category: "웹디자인",
    imageUrl: "/home/semifolio/15.png",
    userProfile: "https://picsum.photos/1151",
    userName: "taehyn kang",
    likes: 33,
    views: 523,
    style: "심플한",
    color: "FFFFFF",
  },
  {
    id: 36,
    title: "파마씨",
    category: "그래픽디자인",
    imageUrl: "/home/semifolio/16.jpg",
    userProfile: "https://picsum.photos/1161",
    userName: "고원보",
    likes: 33,
    views: 523,
    style: "심플한",
    color: "70C9FF",
  },
  {
    id: 37,
    title: "UIUX",
    category: "UI/UX",
    imageUrl: "/home/semifolio/17.jpg",
    userProfile: "https://picsum.photos/1171",
    userName: "다수의 크리에이터",
    likes: 33,
    views: 523,
    style: "다채로운",
    color: "FFFFFF",
  },
  {
    id: 38,
    title: "삼성카드 웹리뉴얼",
    category: "UI/UX",
    imageUrl: "/home/semifolio/18.jpg",
    userProfile: "https://picsum.photos/1181",
    userName: "Star",
    likes: 33,
    views: 523,
    style: "심플한",
    color: "FFFFFF",
  },
  {
    id: 39,
    title: "Plofello",
    category: "UI/UX",
    imageUrl: "/home/semifolio/19.jpg",
    userProfile: "https://picsum.photos/1191",
    userName: "다수의 크리에이터",
    likes: 33,
    views: 523,
    style: "심플한",
    color: "FFFFFF",
  },
  {
    id: 40,
    title: "'Handmade' Greyscalegorilla Plus",
    category: "산업디자인",
    imageUrl: "/home/semifolio/20.jpg",
    userProfile: "https://picsum.photos/1201",
    userName: "Dan Zucco",
    likes: 33,
    views: 523,
    style: "다채로운",
    color: "FFF500",
    pick: true,
  },
];

export default SemifolioDatas;