const SemifolioDatas = [
  {
    id: 1,
    title: "스팩폴리오 프로젝트1",
    category: "UI/UX",
    imageUrl: "https://picsum.photos/1010",
    userProfile: "https://picsum.photos/1001",
    userName: "jimin1",
    likes: 3,
    views: 5,
    
  },
  {
    id: 2,
    title: "스팩폴리오 프로젝트2",
    category: "WEB",
    imageUrl: "https://picsum.photos/1020",
    userProfile: "https://picsum.photos/1021",
    userName: "jimin2",
    likes: 35,
    views: 235,
    pick: true,
  },
  { 
    id: 3,
    title: "스팩폴리오 프로젝트3",
    category: "그래픽",
    imageUrl: "https://picsum.photos/1030",
    userProfile: "https://picsum.photos/1031",
    userName: "jimin3",
    likes: 33,
    views: 45,
  },
  {
    id: 4,
    title: "스팩폴리오 프로젝트4",
    category: "제품",
    imageUrl: "https://picsum.photos/1040",
    userProfile: "https://picsum.photos/1041",
    userName: "jimin4",
    likes: 32,
    views: 53,
  },
  {
    id: 5,
    title: "스팩폴리오 프로젝트5",
    category: "광고",
    imageUrl: "https://picsum.photos/1050",
    userProfile: "https://picsum.photos/1051",
    userName: "jimin5",
    likes: 33,
    views: 523,
  },
  {
    id: 6,
    title: "스팩폴리오 프로젝트6",
    category: "시각",
    imageUrl: "https://picsum.photos/1060",
    userProfile: "https://picsum.photos/1061",
    userName: "jimin6",
    likes: 3,
    views: 5,
  },
  {
    id: 7,
    title: "스팩폴리오 프로젝트7",
    category: "일러스트레이션",
    imageUrl: "https://picsum.photos/1070",
    userProfile: "https://picsum.photos/1071",
    userName: "jimin7",
    likes: 35,
    views: 235,
  },
  {
    id: 8,
    title: "스팩폴리오 프로젝트8",
    category: "캐릭터",
    imageUrl: "https://picsum.photos/1080",
    userProfile: "https://picsum.photos/1081",
    userName: "jimin8",
    likes: 33,
    views: 45,
  },
  {
    id: 9,
    title: "스팩폴리오 프로젝트9",
    category: "공간",
    imageUrl: "https://picsum.photos/1090",
    userProfile: "https://picsum.photos/1091",
    userName: "jimin9",
    likes: 32,
    views: 53,
  },
  {
    id: 10,
    title: "스팩폴리오 프로젝트10",
    category: "패션",
    imageUrl: "https://picsum.photos/1100",
    userProfile: "https://picsum.photos/1101",
    userName: "jimin10",
    likes: 33,
    views: 523,
  },
  {
    id: 11,
    title: "스팩폴리오 프로젝트11",
    category: "3D",
    imageUrl: "https://picsum.photos/1110",
    userProfile: "https://picsum.photos/1111",
    userName: "jimin11",
    likes: 33,
    views: 523,
  },
  {
    id: 12,
    title: "스팩폴리오 프로젝트12",
    category: "영상/모션그래픽",
    imageUrl: "https://picsum.photos/1120",
    userProfile: "https://picsum.photos/1121",
    userName: "jimin12",
    likes: 33,
    views: 523,
  },
  {
    id: 13,
    title: "스팩폴리오 프로젝트13",
    category: "편집",
    imageUrl: "https://picsum.photos/1130",
    userProfile: "https://picsum.photos/1131",
    userName: "jimin13",
    likes: 33,
    views: 523,
  },
  {
    id: 14,
    title: "스팩폴리오 프로젝트14",
    category: "브랜딩",
    imageUrl: "https://picsum.photos/1140",
    userProfile: "https://picsum.photos/1141",
    userName: "jimin14",
    likes: 33,
    views: 523,
  },
  {
    id: 15,
    title: "스팩폴리오 프로젝트15",
    category: "브랜딩",
    imageUrl: "https://picsum.photos/1150",
    userProfile: "https://picsum.photos/1151",
    userName: "jimin15",
    likes: 33,
    views: 523,
  },
  {
    id: 16,
    title: "스팩폴리오 프로젝트16",
    category: "브랜딩",
    imageUrl: "https://picsum.photos/1160",
    userProfile: "https://picsum.photos/1161",
    userName: "jimin16",
    likes: 33,
    views: 523,
  },
  {
    id: 17,
    title: "스팩폴리오 프로젝트17",
    category: "브랜딩",
    imageUrl: "https://picsum.photos/1170",
    userProfile: "https://picsum.photos/1171",
    userName: "jimin17",
    likes: 33,
    views: 523,
    pick: true,
  },
  {
    id: 18,
    title: "스팩폴리오 프로젝트18",
    category: "브랜딩",
    imageUrl: "https://picsum.photos/1180",
    userProfile: "https://picsum.photos/1181",
    userName: "jimin18",
    likes: 33,
    views: 523,
  },
  {
    id: 19,
    title: "스팩폴리오 프로젝트19",
    category: "브랜딩",
    imageUrl: "https://picsum.photos/1190",
    userProfile: "https://picsum.photos/1191",
    userName: "jimin19",
    likes: 33,
    views: 523,
  },
  {
    id: 20,
    title: "스팩폴리오 프로젝트20",
    category: "브랜딩",
    imageUrl: "https://picsum.photos/1200",
    userProfile: "https://picsum.photos/1201",
    userName: "jimin20",
    likes: 33,
    views: 523,
  },
  {
    id: 21,
    title: "스팩폴리오 프로젝트21",
    category: "브랜딩",
    imageUrl: "https://picsum.photos/1210",
    userProfile: "https://picsum.photos/1211",
    userName: "jimin21",
    likes: 33,
    views: 523,
  },
  {
    id: 22,
    title: "스팩폴리오 프로젝트22",
    category: "브랜딩",
    imageUrl: "https://picsum.photos/1220",
    userProfile: "https://picsum.photos/1221",
    userName: "jimin22",
    likes: 33,
    views: 523,
  },
  {
    id: 23,
    title: "스팩폴리오 프로젝트23",
    category: "브랜딩",
    imageUrl: "https://picsum.photos/1230",
    userProfile: "https://picsum.photos/1231",
    userName: "jimin23",
    likes: 33,
    views: 523,
  },
  {
    id: 24,
    title: "스팩폴리오 프로젝트24",
    category: "브랜딩",
    imageUrl: "https://picsum.photos/1240",
    userProfile: "https://picsum.photos/1241",
    userName: "jimin24",
    likes: 33,
    views: 523,
  },
  {
    id: 25,
    title: "스팩폴리오 프로젝트25",
    category: "브랜딩",
    imageUrl: "https://picsum.photos/1250",
    userProfile: "https://picsum.photos/1251",
    userName: "jimin25",
    likes: 33,
    views: 523,
  },
  {
    id: 26,
    title: "스팩폴리오 프로젝트26",
    category: "브랜딩",
    imageUrl: "https://picsum.photos/1260",
    userProfile: "https://picsum.photos/1261",
    userName: "jimin26",
    likes: 33,
    views: 523,
  },
  {
    id: 27,
    title: "스팩폴리오 프로젝트27",
    category: "브랜딩",
    imageUrl: "https://picsum.photos/1270",
    userProfile: "https://picsum.photos/1271",
    userName: "jimin27",
    likes: 33,
    views: 523,
  },
  {
    id: 28,
    title: "스팩폴리오 프로젝트28",
    category: "브랜딩",
    imageUrl: "https://picsum.photos/1280",
    userProfile: "https://picsum.photos/1281",
    userName: "jimin28",
    likes: 33,
    views: 528,
  },
  {
    id: 29,
    title: "스팩폴리오 프로젝트29",
    category: "브랜딩",
    imageUrl: "https://picsum.photos/1290",
    userProfile: "https://picsum.photos/1291",
    userName: "jimin29",
    likes: 33,
    views: 523,
  },
  {
    id: 30,
    title: "스팩폴리오 프로젝트30",
    category: "브랜딩",
    imageUrl: "https://picsum.photos/1300",
    userProfile: "https://picsum.photos/1301",
    userName: "jimin30",
    likes: 33,
    views: 523,
  },
  {
    id: 31,
    title: "스팩폴리오 프로젝트31",
    category: "브랜딩",
    imageUrl: "https://picsum.photos/1310",
    userProfile: "https://picsum.photos/1311",
    userName: "jimin31",
    likes: 33,
    views: 523,
  },
  {
    id: 32,
    title: "스팩폴리오 프로젝트32",
    category: "브랜딩",
    imageUrl: "https://picsum.photos/1320",
    userProfile: "https://picsum.photos/1321",
    userName: "jimin32",
    likes: 33,
    views: 523,
  },
  {
    id: 33,
    title: "스팩폴리오 프로젝트33",
    category: "브랜딩",
    imageUrl: "https://picsum.photos/1330",
    userProfile: "https://picsum.photos/1331",
    userName: "jimin33",
    likes: 33,
    views: 523,
  },
  {
    id: 34,
    title: "스팩폴리오 프로젝트34",
    category: "브랜딩",
    imageUrl: "https://picsum.photos/1340",
    userProfile: "https://picsum.photos/1341",
    userName: "jimin34",
    likes: 33,
    views: 523,
  },
  {
    id: 35,
    title: "스팩폴리오 프로젝트35",
    category: "브랜딩",
    imageUrl: "https://picsum.photos/1350",
    userProfile: "https://picsum.photos/1351",
    userName: "jimin35",
    likes: 33,
    views: 523,
  },
  {
    id: 36,
    title: "스팩폴리오 프로젝트36",
    category: "브랜딩",
    imageUrl: "https://picsum.photos/1360",
    userProfile: "https://picsum.photos/1361",
    userName: "jimin36",
    likes: 33,
    views: 523,
  },
  {
    id: 37,
    title: "스팩폴리오 프로젝트37",
    category: "브랜딩",
    imageUrl: "https://picsum.photos/1370",
    userProfile: "https://picsum.photos/1371",
    userName: "jimin37",
    likes: 33,
    views: 523,
  },
  {
    id: 38,
    title: "스팩폴리오 프로젝트38",
    category: "브랜딩",
    imageUrl: "https://picsum.photos/1380",
    userProfile: "https://picsum.photos/1381",
    userName: "jimin38",
    likes: 33,
    views: 523,
  },
  {
    id: 39,
    title: "스팩폴리오 프로젝트39",
    category: "브랜딩",
    imageUrl: "https://picsum.photos/1390",
    userProfile: "https://picsum.photos/1391",
    userName: "jimin39",
    likes: 33,
    views: 523,
  },
  {
    id: 40,
    title: "스팩폴리오 프로젝트40",
    category: "브랜딩",
    imageUrl: "https://picsum.photos/1400",
    userProfile: "https://picsum.photos/1401",
    userName: "jimin40",
    likes: 33,
    views: 523,
  },
  {
    id: 41,
    title: "스팩폴리오 프로젝트41",
    category: "브랜딩",
    imageUrl: "https://picsum.photos/1410",
    userProfile: "https://picsum.photos/1411",
    userName: "jimin41",
    likes: 33,
    views: 523,
  },
  {
    id: 42,
    title: "스팩폴리오 프로젝트42",
    category: "브랜딩",
    imageUrl: "https://picsum.photos/1420",
    userProfile: "https://picsum.photos/1421",
    userName: "jimin42",
    likes: 33,
    views: 523,
  },
  {
    id: 43,
    title: "스팩폴리오 프로젝트43",
    category: "브랜딩",
    imageUrl: "https://picsum.photos/1430",
    userProfile: "https://picsum.photos/1431",
    userName: "jimin43",
    likes: 33,
    views: 523,
  },
];

export default SemifolioDatas;